### ISSUE TITLE
I can reorder news

### ISSUE THREAD

**Issue by ryanmitchell** [enespolat24/example-case#1]
I take it news is the collection youre having issues with?

When i apply this PR: https://github.com/statamic/eloquent-driver/pull/57
And re-order, this is what I see:

https://user-images.githubusercontent.com/51899/191671889-a7bfdcbf-8fd1-4d4c-b3e0-d1588ea1e4c2.mov

So it seems to be working fine...

**Comment by enespolat24** [comment]
but when you save , ordering doesn't save the way you order

**Comment by ryanmitchell** [comment]
It does - you can you see that in the video?

**Comment by enespolat24** [comment]
yes , i see that and i wanted to try but i got this error while saving reordering. i guess i'm super unlucky nowadays
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/21336979/191731905-81a1512a-3309-496f-a168-bcee56555515.png">

**Comment by ryanmitchell** [comment]
Are you on the very latest statamic version? 
Is your data the same as what you supplied me? 
What is your updated_at column type set to be?

**Comment by enespolat24** [comment]
yes the data is the same as i supplied. i tried at this project. 
updated_at column type is timestamp but i have this error with other projects as well. 

when i click save button again. it saves but reordering doesn't apply at all. here i recorded a loom 
https://www.loom.com/share/f6602591128a46f3bcb38c1b890a2df7

**Comment by enespolat24** [comment]
it did when i made strict => false. 
thank you so much. I really appreciate your help sir

**Comment by ryanmitchell** [comment]
Great, glad to help
